monitor=,preferred,auto,1.2
monitor=,highres,auto,1

# Laptop Main Monitor
monitor = eDP-1, preferred, 0x0, 1

# Old DELL Vertical
monitor = HDMI-A-1, preferred, 1920x0, 1, transform, 1
# monitor = desc:AOC AG273QS4R4 0x00000346, preferred, -2560x-800, 1

workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1

workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
